replicaCount: 1

spring:
  profiles:
    active: "prod"
env:
  - name: JAVA_TOOL_OPTIONS
    value: "-XX:MaxRAMPercentage=75.0 -XX:+UseG1GC -XX:MaxGCPauseMillis=200"

vault:
  role: link-shortener-link-service-prod-role
  secretPath: kv/data/prod/link-shortener-link-service/config
  secretTemplate: |
    {{- with secret "kv/data/prod/link-shortener-link-service/config" -}}
    {{- range $key, $value := .Data.data }}
    {{ $key }}={{ $value }}
    {{- end }}
    {{- end }}
